---
nvidia_container_toolkit_version: 1.18.1-1

packages:
  - curl
  - vim
  - gnome-terminal
  - gnupg2
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - python3-venv
  - "nvidia-container-toolkit={{ nvidia_container_toolkit_version }}"
  - "nvidia-container-toolkit-base={{ nvidia_container_toolkit_version }}"
  - "libnvidia-container-tools={{ nvidia_container_toolkit_version }}"
  - "libnvidia-container1={{ nvidia_container_toolkit_version }}"

media_mount: /media
media_base: "{{ media_mount}}/Media"
pvr_directories:
  - "{{ media_base }}"
  - "{{ media_base }}/Movies"
  - "{{ media_base }}/TV"
  - "{{ media_base }}/Music"
  - "{{ media_base }}/Books"
  - "{{ media_base }}/Audiobooks"
  - "{{ media_base }}/Torrents"
  - "{{ media_base }}/Downloads/Complete"
  - "{{ media_base }}/Downloads/Incomplete"

appdata_base: /appdata
appdata_directories:
  - "{{ appdata_base }}"
  - "{{ appdata_base }}/lidarr"
  - "{{ appdata_base }}/radarr"
  - "{{ appdata_base }}/sonarr"
  - "{{ appdata_base }}/prowlarr"
  - "{{ appdata_base }}/readarr"
  - "{{ appdata_base }}/plex"
  - "{{ appdata_base }}/plex/transcode"
  - "{{ appdata_base }}/gluetun"
  - "{{ appdata_base }}/qbittorrent"
  - "{{ appdata_base }}/jackett"
  - "{{ appdata_base }}/sabnzbd"
