---
ubuntu_username: plex
nvidia_container_toolkit_version: 1.18.1-1

install_packages:
  - curl
  - vim
  - gnome-terminal
  - gnupg2
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - python3-venv
  - zfsutils-linux
  - "nvidia-container-toolkit={{ nvidia_container_toolkit_version }}"
  - "nvidia-container-toolkit-base={{ nvidia_container_toolkit_version }}"
  - "libnvidia-container-tools={{ nvidia_container_toolkit_version }}"
  - "libnvidia-container1={{ nvidia_container_toolkit_version }}"

zfs_pool: "/pool/data/media"
pvr_directories:
  - "{{ zfs_pool }}"
  - "{{ zfs_pool }}/Movies"
  - "{{ zfs_pool }}/TV"
  - "{{ zfs_pool }}/Music"
  - "{{ zfs_pool }}/Books"
  - "{{ zfs_pool }}/Audiobooks"
  - "{{ zfs_pool }}/Torrents"
  - "/home/{{ ubuntu_username }}/Downloads"
  - "/home/{{ ubuntu_username }}/Downloads/Complete"
  - "/home/{{ ubuntu_username }}/Downloads/Incomplete"

appdata_base: /appdata
appdata_directories:
  - "{{ appdata_base }}"
  - "{{ appdata_base }}/lidarr"
  - "{{ appdata_base }}/radarr"
  - "{{ appdata_base }}/sonarr"
  - "{{ appdata_base }}/prowlarr"
  - "{{ appdata_base }}/readarr"
  - "{{ appdata_base }}/plex/config"
  - "{{ appdata_base }}/plex/transcode"
  - "{{ appdata_base }}/gluetun"
  - "{{ appdata_base }}/qbittorrent"
  - "{{ appdata_base }}/jackett"
  - "{{ appdata_base }}/sabnzbd"
  - "{{ appdata_base }}/tautulli"
  - "{{ appdata_base }}/homeassistant"
  - "{{ appdata_base }}/portainer"
  - "{{ appdata_base }}/nginx_proxy_manager"
  - "{{ appdata_base }}/nginx_proxy_manager_letsencrypt"
  - "{{ appdata_base }}/beszel"
  - "{{ appdata_base }}/beszel_agent"
  - "{{ appdata_base }}/beszel_socket"
  - "{{ appdata_base }}/overseerr"
  - "{{ appdata_base }}/vaultwarden"
  - "{{ appdata_base }}/duplicati"
  - "{{ appdata_base }}/uptime_kuma"
