---

- name: Import tasks from packages.yml
  ansible.builtin.import_tasks: packages.yml

- name: Import tasks from system.yml
  ansible.builtin.import_tasks: system.yml
  tags:
    - system

- name: Import tasks from pvr.yml
  ansible.builtin.import_tasks: pvr.yml
  tags:
    - pvr
