services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /appdata/beszel:/beszel_data
      - /appdata/beszel_socket:/beszel_socket
    healthcheck:
      test: [ 'CMD', '/beszel', 'health', '--url', 'http://localhost:8090' ]
      start_period: 30s
      interval: 120s

  beszel-agent:
    image: henrygd/beszel-agent-nvidia:latest
    container_name: beszel-agent
    restart: unless-stopped
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities:
                  - utility
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /appdata/beszel_agent:/var/lib/beszel-agent
      - /pool/data/.beszel:/extra-filesystems/zpool:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILSeJcM3/98yB9JieQFmCUd/bPOCB0JMkWJ97resDbdG'
      TOKEN: 812e-c47e10a02-554c-b5ea75c08
      HUB_URL: http://192.168.1.15:8090
      # gui Host/ip /beszel_socket/beszel.sock

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /appdata/portainer:/data
    ports:
      - 9443:9443
      - 9000:9000
      # - 8000:8000 # Remove if you do not intend to use Edge Agents

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /appdata/nginx_proxy_manager:/data
      - /appdata/nginx_proxy_manager_letsencrypt:/etc/letsencrypt
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:81/api" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant"
    volumes:
      - /appdata/homeassistant_config:/config
    restart: unless-stopped
    ports:
      - 8123:8123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8123" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /appdata/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8181/status" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - /appdata/vaultwarden:/data
    ports:
      - 8000:80
    environment:
      - DOMAIN=https://v.jaybot.us
      - SIGNUPS_ALLOWED=false
      - TZ=America/Los_Angeles
    env_file:
      - /home/plex/.gmail_smtp
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - TZ=America/Los_Angeles
    env_file:
      - /home/plex/.watchtower
    restart: unless-stopped

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    env_file:
      - /home/plex/.duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Los_Angeles
      - CLI_ARGS= #optional
    volumes:
      - /appdata/duplicati:/config
      - /pool/data/backups:/backups
      - /appdata:/source
    ports:
      - 8200:8200
    restart: unless-stopped